// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bahrain_api.Data;

namespace bahrain_api.Migrations
{
    [DbContext(typeof(BahrainDataContext))]
    partial class BahrainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bahrain_api.Models.ATController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApprovedPositions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSignOff")
                        .HasColumnType("bit");

                    b.Property<string>("HomeVacc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnSolo")
                        .HasColumnType("bit");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<bool>("Visitor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("atcontrollers");
                });

            modelBuilder.Entity("bahrain_api.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionPower")
                        .HasColumnType("int");

                    b.Property<string>("StaffCallsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StaffMember");
                });
#pragma warning restore 612, 618
        }
    }
}
